# Generated by Django 5.2.7 on 2025-11-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad (en años)'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='M', max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
